version: '2.3'
services:
  elvis_api:
    build: .
    env_file: .env
    restart: always
    links:
      - orientdb
    volumes:
      - /var/lib/elvis/rawdata:/rawdata:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "3"
  orientdb:
    image: orientdb:3.0.4
    restart: always
    environment:
      - ORIENTDB_ROOT_PASSWORD=$ORIENTDB_ROOT_PASSWORD
      - Xmx=$Xmx
    mem_limit: $ORIENTDB_MEMORY_LIMIT
